### ISSUE TITLE
Add Signature information for Semanticdb

### ISSUE THREAD

**Issue by tanishiking** [scala/scala3#12766]
## Background
Current `SemanticdbExtractor` in Scala3 doesn't extract `` [Signature](https://scalameta.org/docs/semanticdb/specification.html#signature) information, which represents the type information for class, method, type, and local value.

Actually, from the following scala code,

```
class Simple {
  val a = 123
  a + a
}
```

symbols section will look like:

<details><summary>Scala 2</summary>
<p>

```scala
 Vector(
        SymbolInformation(
          "_empty_/Simple#",
          SCALA,
          CLASS,
          0,
          "Simple",
          ClassSignature(
            Some(Scope(Vector(), Vector())),
            Vector(TypeRef(Empty, "scala/AnyRef#", Vector())),
            Empty,
            Some(Scope(Vector("_empty_/Simple#`<init>`().", "_empty_/Simple#a."), Vector()))
          ),
          Vector(),
          PublicAccess()
        ),
        SymbolInformation(
          "_empty_/Simple#`<init>`().",
          SCALA,
          CONSTRUCTOR,
          8192,
          "<init>",
          MethodSignature(Some(Scope(Vector(), Vector())), Vector(Scope(Vector(), Vector())), Empty),
          Vector(),
          PublicAccess()
        ),
        SymbolInformation(
          "_empty_/Simple#a.",
          SCALA,
          METHOD,
          1024,
          "a",
          MethodSignature(
            Some(Scope(Vector(), Vector())),
            Vector(),
            TypeRef(Empty, "scala/Int#", Vector())
          ),
          Vector(),
          PublicAccess()
        )
      ),
```

compared to Scala 3 which is missing all information about signatures. 
</p>
</details>

<details><summary>Scala 3</summary>
<p>

```scala
      Vector(
        SymbolInformation("_empty_/Simple#", SCALA, CLASS, 0, "Simple", Empty, Vector(), Empty),
        SymbolInformation(
          "_empty_/Simple#`<init>`().",
          SCALA,
          CONSTRUCTOR,
          8192,
          "<init>",
          Empty,
          Vector(),
          Empty
        ),
        SymbolInformation("_empty_/Simple#a.", SCALA, METHOD, 1024, "a", Empty, Vector(), Empty)
      ),
```

</p>
</details>

(copied from https://github.com/scalameta/metals/discussions/2593#discussioncomment-512502)

Without `Signature` information in extracted SemanticDB, devtools based on Semanticdb lacks some functionalities for Scala3.
For example, `metals` can't provide `textDocument/implementation` and` type decorations` features for scala3 project, we can't implement scalafix rules that depends on Signature information.

---

## TODOs
- [x] Generate Semanticdb's data structures (e.g. `SymbolInformation`, `ClassSignature`, and etc, see https://scalameta.org/docs/semanticdb/specification.html#data-model)
  - Some 
data structures are already defined [here  https://github.com/lampepfl/dotty/tree/b7d2a122555a6aa44cc7590852a80f12512c535e/compiler/src/dotty/tools/dotc/semanticdb]. They are copy-paste from generated code and adjusted for Scala3.
    - https://github.com/scalameta/metals/discussions/2593#discussioncomment-529949
- [ ] Extend Semanticdb proto for new Scala3 types
  - [Type Lambdas](https://dotty.epfl.ch/docs/reference/new-types/type-lambdas.html)
  - [Match Types](https://dotty.epfl.ch/docs/reference/new-types/match-types.html)
  - [Dependent Function Types](https://dotty.epfl.ch/docs/reference/new-types/dependent-function-types.html)
  - [Polymorphic Function Types](https://dotty.epfl.ch/docs/reference/new-types/polymorphic-function-types.html)
  - Semanticdb already have `Union Type` and `Intersection Type`
- [x] Extract `Sginature` information for Scala3

### (details) Generate Semanticdb's data structures
As discussed here https://github.com/scalameta/scalameta/issues/2367 , it would be a good first step to keep copy-and-paste and adjust the generated scala codes.
However, hand-crafting all those data-structure (because there's a lot of data structures that related to `Signature`) is tedious and it makes harder to catch-up new version of `scalapb` or new `scalameta.proto`. 

Therefore, we'll create a project that generate the Scala code from `scalameta.proto` using `Scalapb`, and adjust them using `scalafix` (so that Scala3 compiler doesn't need to have dependency on `scalapb-runtime`.

**Comment by tanishiking** [comment]
Opened issues we mentioned in https://github.com/lampepfl/dotty/pull/12885

- https://github.com/lampepfl/dotty/issues/13270
- https://github.com/lampepfl/dotty/issues/13291
- https://github.com/scalameta/scalameta/issues/2450
