### ISSUE TITLE
3.4.0 & 3.4.1-RC1 Release procedure

### ISSUE THREAD

**Issue by Kordyjan** [scala/scala3#19679]
### Switch development from 3.4.1 to 3.4.2
- [x] Create branch `release-3.4.1` from `main`
- [x] On `main`  in `Build.scala`: Set `baseVersion` to `3.4.2`:
  - https://github.com/lampepfl/dotty/pull/19683

### Publish 3.4.0 artifacts to Maven Central via CI:
- [x] On `release-3.4.0` branch:
  - [x] In `Build.scala`: Set `baseVersion` to `3.4.0`
  - [x] In `Build.scala`: Set `previousDottyVersion` to `3.3.1`
  - [x] Set the TASTy version to `28.4-0`
  - [x] In `changelogs` add file with a changelog
- [x] Tag the branch as `3.4.0`
- [Build](https://github.com/lampepfl/dotty/actions/runs/7900678950)
  
### Set bootstrapping for future versions on `main`:
- [x] In `Build.scala`: Set `previousDottyVersion` to `3.4.0`
- [x] In `Build.scala`: Set `referenceVersion` to `3.4.0`
- [x] Check and update `project/MiMaFilters.scala`
 
### Publish 3.4.1-RC1 artifacts to Maven Central via CI:
- [x] On `release-3.4.1` branch
  - [x] In `Build.scala`: Set `previousDottyVersion` to `3.4.0`
  - [x] In `Build.scala`: Set `referenceVersion` to `3.4.0`
  - [x] In `Build.scala`: Set `baseVersion` to `3.4.1-RC1`
  - [x] Check and update `project/MiMaFilters.scala`
  - [x] In `changelogs` add file with a changelog
- [x] Tag the branch as `3.4.1-RC1`
- [Build](https://github.com/lampepfl/dotty/actions/runs/7904678726) 
  
### Set bootstrapping for future versions version on `main`:
- [x] In `Build.scala`: Set `previousDottyVersion` to `3.4.0`
- [ ] In `Build.scala`: Set `referenceVersion` to `3.4.1-RC1`:
  - https://github.com/lampepfl/dotty/pull/19829 
- [x] Check and update `project/MiMaFilters.scala`

### Confirm that the tooling is working correctly:
- Metals (@tgodzik):
  - [x] 3.4.0
  - [x] 3.4.1-RC1
- Scala CLI:
  - [x] 3.4.0
  - [x] 3.4.1-RC1
- Scala Native (@WojciechMazur):
  - [x] 3.4.0
  - [x] 3.4.1-RC1
- Scastie:
  - [x] 3.4.0
  - [x] 3.4.1-RC1
- Scala DAP (@adpi2):
  - [x] 3.4.0
  - [x] 3.4.1-RC1

### Update the ecosystem:
- [x] Release 3.4.0 to SDKMAN
- [x] Update the templates and examples projects:
  - [x] [scala3-mill-example-project](https://github.com/scala/scala3-mill-example-project):
    - https://github.com/scala/scala3-mill-example-project/pull/22
  - [x] [scala3-cross.g8](https://github.com/scala/scala3-cross.g8)
    - https://github.com/scala/scala3-cross.g8/pull/99
  - [x] [scala3-staging.g8](https://github.com/scala/scala3-staging.g8)
    - https://github.com/scala/scala3-staging.g8/pull/45
  - [x] [scala3-tasty-inspector.g8](https://github.com/scala/scala3-tasty-inspector.g8)
    - https://github.com/scala/scala3-tasty-inspector.g8/pull/40
  - [x] [scala3.g8](https://github.com/scala/scala3.g8)
    - https://github.com/scala/scala3.g8/pull/136

### Prepare the documentation:
- [x] Merge `release-3.4.0` into `language-reference-stable`
- [x] Publish API docs for 3.4.0
- [x] Add 3.4.0 to the version list in API docs
- [x] Update [docs.scala-lang](https://github.com/scala/docs.scala-lang)

### Announce the releases:
- [x] Make both GitHub releases public
- [x] Publish a post on https://scala-lang.org/blog
- [x] Open the 3.4.1 tracking thread on https://contributors.scala-lang.org
- [x] Close the 3.4.0 milestone
- [x] Make sure all PRs merged and issues fixed in 3.4.1 are in the 3.4.1 milestone
