### ISSUE TITLE
3.4.1-RC2 Release procedure

### ISSUE THREAD

**Issue by Kordyjan** [scala/scala3#19932]
- [x] Publish 3.4.1-RC2 artifacts to Maven via CI
   - [x] On `release-3.4.1` branch:
     - [x] In `changelogs` add file with a changelog
     - [x] In `Build.scala`: Set `baseVersion` to `3.4.1-RC2`
     - [x] In `Build.scala`: Set `previousDottyVersion` to `3.4.1-RC1`
     - [x] Tag the branch as `3.4.1-RC2`
- [x] Wait for confirmation from tooling:
  - [x] Metals
  - [x] Scala CLI 
  - [x] Scala Native (@WojciechMazur) 
  - [x] Scastie (@rochala) 
  - [x] Scala DAP (@adpi2) 
- [x] Announce the releases
  - [x] Make GitHub releases public
  - [x] Update the [3.4.1 tracking thread](https://contributors.scala-lang.org/t/3-4-1-release-thread/6582)

**Comment by soronpo** [comment]
I tried it today and found a regression since 3.4.0, but apparently it already existed in 3.4.1-RC1. Need to minimize.

**Comment by soronpo** [comment]
Update, while trying to minimize the regression that appeared from this upgrade I managed to get the error to always show up until I downgraded to 3.0.0. See #19955 
Somehow it was hidden thus far in my library and only showed up when upgrading to 3.4.1-RC1. It could be that my minimization found a different error, but I doubt it.
