### ISSUE TITLE
3.4.1 & 3.4.2-RC1 Release procedure

### ISSUE THREAD

**Issue by Kordyjan** [scala/scala3#20024]
### Switch development from 3.4.2 to 3.5.0
- [x] Create branch `release-3.4.2` from `main`
- [x] On `main`  in `Build.scala`: Set `baseVersion` to `3.5.0`:
  - https://github.com/scala/scala3/pull/20025 

### Publish 3.4.1 artifacts to Maven Central via CI:
- [x] On `release-3.4.1` branch:
  - [x] In `Build.scala`: Set `baseVersion` to `3.4.1`
  - [x] In `Build.scala`: Set `previousDottyVersion` to `3.4.0`
  - [x] Set the TASTy version to `28.4-0`
  - [x] In `changelogs` add file with a changelog
- [x] Tag the branch as `3.4.1`
- [Build](https://github.com/scala/scala3/actions/runs/8452596798)
  
### Set bootstrapping for future versions on `main`:
- [x] In `Build.scala`: Set `previousDottyVersion` to `3.4.1`
- [x] In `Build.scala`: Set `referenceVersion` to `3.4.1`
- [x] Check and update `project/MiMaFilters.scala`
- https://github.com/scala/scala3/pull/20048
 
### Publish 3.4.2-RC1 artifacts to Maven Central via CI:
- [x] On `release-3.4.2` branch
  - [x] In `changelogs` add file with a changelog
  - [x] In `Build.scala`: Set `previousDottyVersion` to `3.4.1`
  - [x] In `Build.scala`: Set `referenceVersion` to `3.4.1`
- [x] Tag the branch as `3.4.2-RC1`
- [Build](https://github.com/scala/scala3/actions/runs/8466642481) 
  
### Set bootstrapping for future versions version on `main`:
- [x] In `Build.scala`: Set `referenceVersion` to `3.4.2-RC1`
- https://github.com/scala/scala3/pull/20048

### Confirm that the tooling is working correctly:
- Metals:
  - [x] 3.4.1
  - [x] 3.4.2-RC1
- Scala CLI:
  - [x] 3.4.1
  - [x] 3.4.2-RC1
- Scala Native:
  - [x] 3.4.1
  - [x] 3.4.2-RC1
- Scastie:
  - [x] 3.4.1
  - [x] 3.4.2-RC1
- Scala DAP:
  - [x] 3.4.1
  - [x] 3.4.2-RC1

### Update the ecosystem:
- [x] Release 3.4.1 to SDKMAN
- [x] Update the templates and examples projects:
  - [x] [scala3-mill-example-project](https://github.com/scala/scala3-mill-example-project):
    - https://github.com/scala/scala3-mill-example-project/pull/23 
  - [x] [scala3-cross.g8](https://github.com/scala/scala3-cross.g8)
    - https://github.com/scala/scala3-cross.g8/pull/102
  - [x] [scala3-staging.g8](https://github.com/scala/scala3-staging.g8)
    - https://github.com/scala/scala3-staging.g8/pull/46
  - [x] [scala3-tasty-inspector.g8](https://github.com/scala/scala3-tasty-inspector.g8)
    - https://github.com/scala/scala3-tasty-inspector.g8/pull/41
  - [x] [scala3.g8](https://github.com/scala/scala3.g8)
    - https://github.com/scala/scala3.g8/pull/138

### Prepare the documentation:
- [x] Merge `release-3.4.1` into `language-reference-stable`
- [x] Publish API docs for 3.4.1
- [x] Add 3.4.1 to the version list in API docs
- [x] Update [docs.scala-lang](https://github.com/scala/docs.scala-lang)
  - https://github.com/scala/docs.scala-lang/pull/3003

### Announce the releases:
- [x] Make both GitHub releases public
- [x] Publish an announcement on https://scala-lang.org/blog:
  - https://github.com/scala/scala-lang/pull/1634
- [x] Open the 3.4.2 tracking thread on https://contributors.scala-lang.org:
  - https://contributors.scala-lang.org/t/3-4-2-release-thread/6613
- [x] Close the 3.4.1 milestone
- [x] Make sure all PRs merged and issues fixed in 3.4.2-RC1 are in the 3.4.2 milestone
