### ISSUE TITLE
3.4.2 & 3.5.0-RC1 Release procedure

### ISSUE THREAD

**Issue by Kordyjan** [scala/scala3#20391]
### Switch development from 3.4.1 to 3.4.2
- [x] Create branch `release-3.5.0` from `main`

### Publish 3.4.2 artifacts to Maven Central via CI:
- [x] On `release-3.4.2` branch:
  - [x] In `Build.scala`: Set `baseVersion` to `3.4.2`
  - [x] In `changelogs` add file with a changelog
- [x] Tag the branch as `3.4.2`
- [Build](https://github.com/scala/scala3/actions/runs/9063114929)
 
### Publish 3.5.0-RC1 artifacts to Maven Central via CI:
- [x] On `release-3.5.0` branch
  - [x] In `Build.scala`: Set `referenceVersion` to `3.4.2`
  - [x] In `changelogs` add file with a changelog
- [x] Tag the branch as `3.5.0-RC1`
- ~[Build](https://github.com/scala/scala3/actions/runs/9079516691)~
- [Build](https://github.com/scala/scala3/actions/runs/9085241763) 
  
### Set bootstrapping for future versions version on `main`:
- [x] In `Build.scala`: Set `referenceVersion` to `3.5.0-RC1`:
- [x] Check and update `project/MiMaFilters.scala`

### Confirm that the tooling is working correctly:
- Metals:
  - [x] 3.4.2
  - [x] 3.5.0-RC1
- Scala Native:
  - [x] 3.4.2
  - [x] 3.5.0-RC1
- Scastie:
  - [x] 3.4.2
  - [x] 3.5.0-RC1
- Scala DAP:
  - [x] 3.4.2
  - [x] 3.5.0-RC1
- Scala CLI:
  - [x] 3.4.2
  - [x] 3.5.0-RC1

### Update the ecosystem:
- [x] Release 3.4.2 to SDKMAN
- [x] Update the templates and examples projects:
  - [x] [scala3-mill-example-project](https://github.com/scala/scala3-mill-example-project):
    - https://github.com/scala/scala3-mill-example-project/pull/24
  - [x] [scala3-cross.g8](https://github.com/scala/scala3-cross.g8):
    - https://github.com/scala/scala3-cross.g8/pull/105
  - [x] [scala3-staging.g8](https://github.com/scala/scala3-staging.g8):
    - https://github.com/scala/scala3-staging.g8/pull/47
  - [x] [scala3-tasty-inspector.g8](https://github.com/scala/scala3-tasty-inspector.g8):
     - https://github.com/scala/scala3-tasty-inspector.g8/pull/42
  - [x] [scala3.g8](https://github.com/scala/scala3.g8):
    - https://github.com/scala/scala3.g8/pull/143

### Prepare the documentation:
- [x] Merge `release-3.4.2` into `language-reference-stable`
- [x] Publish API docs for 3.4.2
- [x] Add 3.4.2 to the version list in API docs
- [x] Update [docs.scala-lang](https://github.com/scala/docs.scala-lang):
  - https://github.com/scala/docs.scala-lang/pull/3022

### Announce the releases:
- [x] Make both GitHub releases public:
  - [x] 3.4.2
  - [x] 3.5.0-RC1
- [x] Publish an announcement on https://scala-lang.org:
  - https://github.com/scala/scala-lang/pull/1652
- [x] Open the 3.5.0 tracking thread on https://contributors.scala-lang.org:
  - https://contributors.scala-lang.org/t/3-5-0-release-thread/6666
- [x] Unlock Scala Steward updates:
  - https://github.com/scala-steward-org/scala-steward/pull/3358
