### ISSUE TITLE
3.5.0-RC2 Release procedure

### ISSUE THREAD

**Issue by WojciechMazur** [scala/scala3#20653]
- [x] Publish 3.5.0-RC2 artifacts to Maven via CI
   - [x] On `release-3.5.0` branch:
     - [x] In `changelogs` add file with a changelog
     - [x] In `Build.scala`: Set `baseVersion` to `3.5.0-RC2`
     - [x] Tag the branch as `3.5.0-RC2`
     - [x] [CI Build](https://github.com/scala/scala3/actions/runs/9612129433)
- [x] Wait for confirmation from tooling:
  - [x] Metals
  - [x] Scala CLI (@Gedochao)
  - [x] Scala Native (@WojciechMazur) 
  - [x] Scastie (@rochala) 
  - [x] Scala DAP (@adpi2) 
- [x] Announce the releases
  - [x] Make GitHub releases public
  - [x] Update the [3.5.0 tracking thread](https://contributors.scala-lang.org/t/3-5-0-release-thread/6666)

**Comment by OndrejSpanel** [comment]
It seems 3.5.0-RC2 still depends on stdlib 2.13.12, not 2.13.14. See https://mvnrepository.com/artifact/org.scala-lang/scala3-library_3/3.5.0-RC2 Compile Dependencies:

![image](https://github.com/scala/scala3/assets/6927223/48ef07c6-a6a6-40cd-95fd-74d2065e609e)

See also https://users.scala-lang.org/t/what-scala-library-version-is-used-by-which-scala-3-version/9999/6

There are several significant issues fixed in 2.13.14 libraries compared to 2.13.12

**Comment by He-Pin** [comment]
The pom does have that issue

**Comment by OndrejSpanel** [comment]
Related PR #19791

**Comment by WojciechMazur** [comment]
We might need to release an RC3, if so it would also include the Scala 2 dependency upgrade. Otherwise upgrade would be delayed until 3.6 (work on it starts in the upcoming development cycle)
