### ISSUE TITLE
3.5.0-RC4 Release procedure

### ISSUE THREAD

**Issue by WojciechMazur** [scala/scala3#21174]
- [x] Publish 3.5.0-RC4 artifacts to Maven via CI
   - [x] On `release-3.5.0` branch:
     - [x] In `changelogs` add file with a changelog
     - [x] In `Build.scala`: Set `baseVersion` to `3.5.0-RC4`
     - [x] Tag the branch as `3.5.0-RC4`
     - [x] [CI build](https://github.com/scala/scala3/actions/runs/9888051602)
- [x] Wait for confirmation from tooling:
  - [x] Scala CLI (@Gedochao)
  - [x] Scala Native (@WojciechMazur)
  - [x] Scastie (@rochala)
  - [x] Scala DAP (@adpi2)
- [x] Announce the releases
  - [x] Make GitHub releases public
  - [x] Update the [3.5.0 tracking thread](https://contributors.scala-lang.org/t/3-5-0-release-thread/6666)

**Comment by adpi2** [comment]
Released DAP 4.1.1 and 4.2.0
