### ISSUE TITLE
3.3.4-RC1 Release procedure

### ISSUE THREAD

**Issue by WojciechMazur** [scala/scala3#21180]
- [ ] Publish 3.3.4-RC1 artifacts to Maven via CI
   - [x] On `release-3.3.4` branch:
     - [x] In `changelogs` add file with a changelog
     - [x] In `Build.scala`: Set `baseVersion` to `3.3.4-RC1`
     - [x] Tag the branch as `3.3.4-RC1`
     - [ ] [CI build](https://github.com/scala/scala3/actions/runs/9906789116)
- [ ] Wait for confirmation from tooling:
  - [ ] Scala CLI (@Gedochao)
  - [ ] Scala Native (@WojciechMazur)
  - [ ] Scastie (@rochala)
  - [ ] Scala DAP (@adpi2)
- [ ] Announce the releases
  - [ ] Make GitHub releases public
  - [ ] Open up 3.3.4 tracking thread at https://contributors.scala-lang.org

**Comment by adpi2** [comment]
Released DAP 4.1.1 and 4.2.0

**Comment by WojciechMazur** [comment]
Tracking thread: https://contributors.scala-lang.org/t/3-3-4-release-thread/6709
