### ISSUE TITLE
3.5.1-RC1 Release procedure 

### ISSUE THREAD

**Issue by WojciechMazur** [scala/scala3#21193]
- [x] Publish 3.5.1-RC1 artifacts to Maven via CI
   - [x] On `release-3.5.1` branch:
     - [x] In `changelogs` add file with a changelog
     - [x] In `Build.scala`: Set `baseVersion` to `3.5.1-RC1`
     - [x] Tag the branch as `3.5.1-RC1`
     - [x] [CI build](https://github.com/scala/scala3/actions/runs/9927957687)
- [x] Wait for confirmation from tooling:
  - [x] Scala CLI (@Gedochao)
  - [x] Scala Native (@WojciechMazur)
  - [x] Scastie (@rochala)
  - [x] Scala DAP (@adpi2)
- [x] Announce the releases
  - [x] Make GitHub releases public
  - [x] Open up 3.5.1 tracking thread at https://contributors.scala-lang.org

**Comment by smarter** [comment]
Anything still blocking this release?

**Comment by SethTisue** [comment]
iirc, the release team thought it would be confusing to release 3.5.1-RC1 before 3.5.0 final?
