### ISSUE TITLE
3.4.3-RC1 Release procedure

### ISSUE THREAD

**Issue by WojciechMazur** [scala/scala3#21293]
- [x] Publish 3.4.3-RC1 artifacts to Maven via CI
   - [x] On `release-3.4.3` branch:
     - [x] In `changelogs` add file with a changelog
     - [x] In `Build.scala`: Set `baseVersion` to `3.4.3-RC1`
     - [x] Tag the branch as `3.4.3-RC1`
- [x] Wait for confirmation from tooling:
  - [x] Scala CLI (@Gedochao)
  - [x] Scala Native (@WojciechMazur)
  - [x] Scastie (@rochala)
  - [x] Scala DAP (@adpi2)
- [x] Announce the releases
  - [x] Make GitHub releases public
  - [x] Create the 3.4.3 tracking thread on https://contributors.scala-lang.org/

**Comment by OndrejSpanel** [comment]
The text mentions 3.3.4 once and 3.4.3 multiple times, the title mentions 3.4.3. I suppose it should be 3.3.4 everywhere?

**Comment by WojciechMazur** [comment]
> The text mentions 3.3.4 once and 3.4.3 multiple times, the title mentions 3.4.3. I suppose it should be 3.3.4 everywhere?

Thanks, I've fixed the typo. That's the unplanned 3.4.3 hot-fix release due to the binary incompatible change introduced in 3.4.2 and described in #21258. It's only purpose would be to replace the usages of Scala 3.4.2 in projects that cannot/don't want to migrate to 3.5. It would be better described in the upcoming blogpost.
The change introduced in 3.4.2 would eventually be re-introduced in the future, but in more controlled manner in one of next major versions (probably 3.6.0)
