### ISSUE TITLE
3.5.0-RC7 Release procedure

### ISSUE THREAD

**Issue by WojciechMazur** [scala/scala3#21349]
- [x] Publish 3.5.0-RC7 artifacts to Maven via CI
   - [x] On `release-3.5.0` branch:
     - [x] In `changelogs` add file with a changelog
     - [x] In `Build.scala`: Set `baseVersion` to `3.5.0-RC7`
     - [x] Tag the branch as `3.5.0-RC7`
     - [x] Wait for [CI](https://github.com/scala/scala3/actions/runs/10298551609) to finish
- [x] Wait for confirmation from tooling:
  - [x] Scala CLI (@Gedochao)
  - [x] Scala Native (@WojciechMazur)
  - [x] Scastie (@rochala)
  - [x] Scala DAP (@adpi2)
- [x] Announce the releases
  - [x] Make GitHub releases public
  - [x] Update the [3.5.0 tracking thread](https://contributors.scala-lang.org/t/3-5-0-release-thread/6666)

**Comment by adpi2** [comment]
I've done my part: https://repo1.maven.org/maven2/ch/epfl/scala/scala-expression-compiler_3.5.0-RC7/
