### ISSUE TITLE
3.5.0 & 3.5.1-RC2 Release procedure

### ISSUE THREAD

**Issue by Kordyjan** [scala/scala3#21368]
### Publish 3.5.0 artifacts to Maven Central via CI:
- [x] On `release-3.5.0` branch:
  - [x] In `Build.scala`: Set `baseVersion` to `3.5.0`
  - [x] In `changelogs` add file with a changelog
  - [x] Set the TASTy version to `28.5-0`
- [x] Tag the branch as `3.5.0
- ✅ [Build](https://github.com/scala/scala3/actions/runs/10352518931) 
 
### Publish 3.5.1-RC2 artifacts to Maven Central via CI:
- [x] On `release-3.5.1` branch
  - [x] In `Build.scala`: Set `baseVersion` to `3.5.1-RC2`
  - [x] In `Build.scala`: Set `referenceVersion` to `3.5.0`
  - [x] In `changelogs` add file with a changelog
- [x] Tag the branch as `3.5.1-RC2`
- [x] [Build](https://github.com/scala/scala3/actions/runs/10373697026)
  
### Set bootstrapping for future versions version on `main`:
- [x] In `Build.scala`: Set `referenceVersion` to `3.5.1-RC2`:
- [x] Check and update `project/MiMaFilters.scala`

### Confirm that the tooling is working correctly:
- Metals:
  - [ ] 3.5.0
  - [ ] 3.5.1-RC2
- Scala Native:
  - [x] 3.5.0
  - [x] 3.5.1-RC2
- Scastie:
  - [x] 3.5.0
  - [x] 3.5.1-RC2
- Scala DAP:
  - [x] 3.5.0
  - [x] 3.5.1-RC2
- Scala CLI:
  - [x] 3.5.0
  - [x] 3.5.1-RC2

### Update the ecosystem:
- [x] Release 3.5.0 to SDKMAN
- [x] Update the templates and examples projects:
  - [x] [scala3-mill-example-project](https://github.com/scala/scala3-mill-example-project)
  - [x] [scala3-cross.g8](https://github.com/scala/scala3-cross.g8)
  - [x] [scala3-staging.g8](https://github.com/scala/scala3-staging.g8)
  - [x] [scala3-tasty-inspector.g8](https://github.com/scala/scala3-tasty-inspector.g8)
  - [x] [scala3.g8](https://github.com/scala/scala3.g8)

### Prepare the documentation:
- [x] Merge `release-3.5.0` into `language-reference-stable`
- [x] Publish API docs for 3.5.0
- [x] Add 3.5.0 to the version list in API docs
- [x] Update [docs.scala-lang](https://github.com/scala/docs.scala-lang)
  - [x] https://github.com/scala/docs.scala-lang/pull/3062

### Announce the releases:
- [x] Make all GitHub releases public:
  - [x] 3.5.0
  - [x] 3.5.1-RC1
  - [x] 3.5.1-RC2
- [x] Wait for the public availability of the given prioritization post:
  - [x] https://github.com/scala/scala-lang/pull/1675
- [x] Publish an announcement on https://scala-lang.org:
  - https://github.com/scala/scala-lang/pull/1676
- [x] Open the 3.5.1 tracking thread on https://contributors.scala-lang.org
- [x] Unlock Scala Steward updates https://github.com/scala-steward-org/scala-steward/pull/3395

**Comment by adpi2** [comment]
I deployed Scastie with support for both versions. The release of DAP is also in progress.

**Comment by adpi2** [comment]
DAP is released
