### ISSUE TITLE
3.3.4-RC2 Release Procedure

### ISSUE THREAD

**Issue by WojciechMazur** [scala/scala3#21567]
- [x] Publish 3.3.4-RC2 artifacts to Maven via CI
   - [x] On `release-3.3.4` branch:
     - [x] In `changelogs` add file with a changelog
     - [x] In `Build.scala`: Set `baseVersion` to `3.3.4-RC2`
     - [x] Tag the branch as `3.3.4-RC2`
- [x] Wait for confirmation from tooling:
  - [x] Scala CLI (@Gedochao)
  - [x] Scala Native (@WojciechMazur)
  - [ ] Scastie (@rochala)
  - [x] Scala DAP (@adpi2)
- [x] Announce the releases
  - [x] Make GitHub releases public
  - [x] Update the [3.3.4 tracking thread](https://contributors.scala-lang.org/t/3-3-4-release-thread/6709)

**Comment by adpi2** [comment]
Released DAP v4.2.1

The compilation on v4.2.0 is broken and I don't intend to fix it.

**Comment by tgodzik** [comment]
Damn, I think 4.2.0 is used by Bloop 1.6.0 which is the one used by latest stable Metals. I can work on a release this week.
