### ISSUE TITLE
3.3.4-RC3 Release procedure

### ISSUE THREAD

**Issue by WojciechMazur** [scala/scala3#21578]
- [x] Publish 3.3.4-RC3 artifacts to Maven via CI
   - [x] On `release-3.3.4` branch:
     - [x] In `changelogs` add file with a changelog
     - [x] In `Build.scala`: Set `baseVersion` to `3.3.4-RC3`
     - [x] Tag the branch as `3.3.4-RC3`
- [x] Wait for confirmation from tooling:
  - [x] Scala CLI (@Gedochao)
  - [x] Scala Native (@WojciechMazur)
  - [ ] Scala DAP (@adpi2)
- [x] Announce the releases
  - [x] Make GitHub releases public
  - [x] Update the [3.3.4 tracking thread](https://contributors.scala-lang.org/t/3-3-4-release-thread/6709)
