### ISSUE TITLE
3.3.4 release procedure

### ISSUE THREAD

**Issue by WojciechMazur** [scala/scala3#21644]
### Publish 3.3.4 artifacts to Maven Central via CI

- [x] On `release-3.3.4` branch:
  - [x] In `Build.scala`: Set `baseVersion` to `3.3.4`
  - [x] In `changelogs` add file with a changelog
- [x] Tag the branch as `3.3.4`
- [x] Wait for CI to publish artefacts - https://github.com/scala/scala3/actions/runs/11030925031
  
### Set bootstrapping for future versions version on `lts-3.3`

- [x] In `Build.scala`: Set `referenceVersion` to `3.3.4`
- [x] In `Build.scala`: Set `baseVersion` to `3.3.5-RC1`

### Confirm that the tooling is working correctly

- [x] Metals
- [x] Scala Native
- [x] Scastie
- [x] Scala DAP
- [x] Scala CLI
  
### Prepare the documentation

- [x] Publish API docs for 3.3.4
- [x] Add 3.3.4 to the version list in API docs
- [x] Update [docs.scala-lang](https://github.com/scala/docs.scala-lang) - https://github.com/scala/docs.scala-lang/pull/3078

### Announce the releases

- [x] Make GitHub releases `3.3.4` public
- [x] Release 3.3.4 to SDKMAN
- [x] Unlock Scala Steward updates - https://github.com/scala-steward-org/scala-steward/pull/3420
- [x] Publish an announcement on https://scala-lang.org - https://github.com/scala/scala-lang/pull/1698
