### ISSUE TITLE
3.5.2-RC2 Release procedure

### ISSUE THREAD

**Issue by WojciechMazur** [scala/scala3#21745]
- [x] Publish 3.5.2-RC2 artifacts to Maven via CI
   - [x] On `release-3.5.2` branch:
     - [x] In `changelogs` add file with a changelog
     - [x] In `Build.scala`: Set `baseVersion` to `3.5.2-RC2`
     - [x] Tag the branch as `3.5.2-RC2`
     - [x] Wait for [CI to publish artifacts](https://github.com/scala/scala3/actions/runs/11256034069)
- [x] Wait for confirmation from tooling:
  - [x] Scala CLI
  - [x] Scala Native
  - [ ] Scastie
  - [x] Scala DAP
- [x] Announce the releases
  - [x] Make GitHub releases public
  - [x] Update the [3.5.2 tracking thread](https://contributors.scala-lang.org/t/scala-3-5-2-release-thread/6768)
