### ISSUE TITLE
3.5.2 and 3.6.0-RC1 release procedure

### ISSUE THREAD

**Issue by WojciechMazur** [scala/scala3#21781]
### Publish 3.5.2 artifacts to Maven Central via CI

- [x] On `release-3.5.2` branch
  - [x] In `Build.scala`: Set `baseVersion` to `3.5.2`
  - [x] In `TastyFormat.scala`: Set `ExperimentalVersion` to `0`
  - [x] In `changelogs` add file with a changelog
- [x] Tag the branch as `3.5.2`
- [x] [Wait for CI](https://github.com/scala/scala3/actions/runs/11361886736) to publish artifacts

### Publish 3.6.0-RC1 artifacts to Maven Central via CI

- [x] On `release-3.6.0` branch
  - [x] In `Build.scala`: Set `baseVersion` to `3.6.0-RC1`
  - [x] In `Build.scala`: Set `referenceVersion` to `3.5.2`
  - [x] In `changelogs` add file with a changelog
- [x] Tag the branch as `3.6.0-RC1`
- [ ] [Wait for CI](https://github.com/scala/scala3/actions/runs/11394054199) to publish artifacts

### Set bootstrapping for future versions version on `main`

- [x] In `Build.scala`: Set `referenceVersion` to `3.6.0-RC1`:
- [x] Check and update `project/MiMaFilters.scala`

### Confirm that the tooling is working correctly

- Metals:
  - [ ] 3.5.2
  - [ ] 3.6.0
  - [ ] 3.6.1
- Scala Native:
  - [x] 3.5.2
  - [x] 3.6.0
  - [x] 3.6.1
- Scastie:
  - [ ] 3.5.2
  - [ ] 3.6.0
  - [ ] 3.6.1
- Scala DAP:
  - [x] 3.5.2
  - [x] 3.6.0
  - [x] 3.6.1
- Scala CLI:
  - [x] 3.5.2
  - [x] 3.6.0
  - [x] 3.6.1

### Prepare the documentation

- [x] Publish API docs for 3.5.2
- [x] Add 3.5.2 to the version list in API docs
- [x] Set `3.5.2` as default target for `3.x` and `current` docs versions 
- [x] Publish API docs for 3.6.1
- [x] Add 3.5.2 to the version list in API docs
- [x] Update docs.scala-lang https://github.com/scala/docs.scala-lang/pull/3093

### Announce the releases

- [x] Make all GitHub releases public:
  - [x] 3.5.2
  - [x] 3.6.0
  - [x] 3.6.1
- [x] Publish an announcement on <https://scala-lang.org> https://github.com/scala/scala-lang/pull/1707
- [x] Update the 3.5.2 tracking thread on [https://contributors.scala-lang.org](https://contributors.scala-lang.org/t/scala-3-5-2-release-thread/6768/2)
- [x] Open 3.6.0 tracing thread on <https://contributors.scala-lang.org> https://contributors.scala-lang.org/t/scala-3-6-release-thread/6796

### Update the ecosystem

- [x] Release 3.5.2 to SDKMAN
- [x] Release 3.5.2 to Chocolatey @hamzaremmal 
- [x] Update the templates and examples projects:
  - [x] [scala3-mill-example-project](https://github.com/scala/scala3-mill-example-project) https://github.com/scala/scala3-mill-example-project/pull/25
  - [x] [scala3-cross.g8](https://github.com/scala/scala3-cross.g8) https://github.com/scala/scala3-cross.g8/pull/114
  - [x] [scala3-staging.g8](https://github.com/scala/scala3-staging.g8) https://github.com/scala/scala3-staging.g8/pull/57
  - [x] [scala3-tasty-inspector.g8](https://github.com/scala/scala3-tasty-inspector.g8) https://github.com/scala/scala3-tasty-inspector.g8/pull/53
  - [x] [scala3.g8](https://github.com/scala/scala3.g8) https://github.com/scala/scala3.g8/pull/152
- [x] Unlock Scala Steward updates https://github.com/scala-steward-org/scala-steward/pull/3451

**Comment by WojciechMazur** [comment]
Because of error during the release we published 3.6.0-RC1 as 3.6.0 to Maven central. These artifacts cannot be removed. 
To mitigate potential damage (3.6.0 artifact produced TASTy in experimental mode) we shipped 3.6.1 based on 3.6.0-RC1 state but with stable TASTy. 

During Scala 3.6 RC period release 3.6.1 should be treated as 3.6.0-RC1. 
If for some reason during the remaining 5 weeks of RC period there would be no need for any important backports we'd announce 3.6.1 as the first release of Scala 3.6
Otherwise, we would include required changes in Scala 3.6.2 and announce it as first stable release of Scala 3.6. It would involve releasing 3.6.2-RC versions as well.
