### ISSUE TITLE
Scala 3.6.2-RC1 release procedure 

### ISSUE THREAD

**Issue by WojciechMazur** [scala/scala3#21977]
- [x] Publish artifacts to Maven via CI
  - [x] Ensure scala-steward is [blocking automatic upgrades](https://github.com/scala-steward-org/scala-steward/blob/main/modules/core/src/main/resources/default.scala-steward.conf) for `3.6.2` -  https://github.com/scala-steward-org/scala-steward/pull/3479
  - [x] On `release-3.6.2` branch:
    - [x] In `project/Build.scala`: Set `baseVersion = "3.6.2-RC1"`
    - [x] In `tasty/src/dotty/tools/tasty/TastyFormat.scala` ensure `ExperimentalVersion` is set to non-stable (2)
    - [x] Create changelog file in `changelogs/3.6.2-RC1.md`
    - [x] Tag the branch as `3.6.2-RC1`
    - [x] Wait for CI to publish artifacts - https://github.com/scala/scala3/actions/runs/11912756705
    - [x] Audit and release artifacts on https://oss.sonatype.org/
- [x] On `main` branch:
  - [x] In `project/Build.scala`: Set `referenceVersion` to `3.6.2-RC1`
  - [x] Check and update `project/MiMaFilters.scala`
- [x] Wait for releases/confirmation from tooling:
  - [x] Scala CLI - test
  - [x] Scala Native - publish compiler plugin
  - [x] Scastie - update available versions - https://github.com/scalacenter/scastie/pull/1103
  - [x] Scala DAP - publish compiler plugin
- [x] Announce the release
  - [x] Publish release on GitHub Releases (as pre-release)
  - [x] Update tracking thread on [https://contributors.scala-lang.org](https://contributors.scala-lang.org/t/scala-3-6-release-thread/6796/7)
