### ISSUE TITLE
3.6.2-RC2 release procedure

### ISSUE THREAD

**Issue by WojciechMazur** [scala/scala3#22027]
- [x] Publish artifacts to Maven via CI
  - [x] Ensure scala-steward is [blocking automatic upgrades](https://github.com/scala-steward-org/scala-steward/blob/main/modules/core/src/main/resources/default.scala-steward.conf) for `3.6.2`
  - [x] On `release-3.6.2` branch:
    - [x] In `project/Build.scala`: Set `baseVersion = "3.6.2-RC2"`
    - [x] Create changelog file in `changelogs/3.6.2-RC2.md`
    - [x] Tag the branch as `3.6.2-RC2`
    - [x] Wait for CI to publish artifacts - https://github.com/scala/scala3/actions/runs/12028452130
    - [x] Audit and release artifacts on https://oss.sonatype.org/
- [x] Wait for releases/confirmation from tooling:
  - [x] Scala CLI - test
  - [x] Scala Native - publish compiler plugin
  - [x] Scastie - update available versions - https://github.com/scalacenter/scastie/pull/1104
  - [x] Scala DAP - publish compiler plugin
- [x] Announce the release
  - [x] Publish release on GitHub Releases (as pre-release)
  - [x] Update tracking thread on https://contributors.scala-lang.org
