### ISSUE TITLE
3.6.2-RC3 Release Procedure

### ISSUE THREAD

**Issue by WojciechMazur** [scala/scala3#22050]
- [x] Publish artifacts to Maven via CI
  - [x] Ensure scala-steward is [blocking automatic upgrades](https://github.com/scala-steward-org/scala-steward/blob/main/modules/core/src/main/resources/default.scala-steward.conf) for `3.6.2`
  - [x] On `release-3.6.2` branch:
    - [x] In `project/Build.scala`: Set `baseVersion = "3.6.2-RC3"`
    - [x] Create changelog file in `changelogs/3.6.2-RC3.md`
    - [x] Tag the branch as `3.6.2-RC3`
    - [x] Wait for CI to publish artifacts - https://github.com/scala/scala3/actions/runs/12070852822
    - [x] Audit and release artifacts on https://oss.sonatype.org/
- [ ] Wait for releases/confirmation from tooling:
  - [x] Scala CLI - test
  - [x] Scala Native - publish compiler plugin
  - [ ] Scastie - update available versions - https://github.com/scalacenter/scastie/pull/1105
  - [x] Scala DAP - publish compiler plugin - https://github.com/scalacenter/scala-debug-adapter/actions/workflows/release-expression-compiler.yml
- [x] Announce the release
  - [x] Publish release on GitHub Releases (as pre-release)
  - [x] Update tracking thread on https://contributors.scala-lang.org
