### ISSUE TITLE
Scala LTS 3.3.5-RC1 release procedure

### ISSUE THREAD

**Issue by WojciechMazur** [scala/scala3#22169]
- [x] Publish artifacts to Maven via CI
  - [x] Ensure scala-steward is [blocking automatic upgrades](https://github.com/scala-steward-org/scala-steward/blob/main/modules/core/src/main/resources/default.scala-steward.conf) for `3.3.5`
  - [x] On `release-3.3.5` branch:
    - [x] In `project/Build.scala`: Set `baseVersion = "3.3.5-RC1"`
    - [x] In `tasty/src/dotty/tools/tasty/TastyFormat.scala` ensure `ExperimentalVersion` is set to stable (0)
    - [x] Create changelog file in `changelogs/3.3.5-RC1.md`
    - [x] Tag the branch as `3.3.5-RC1`
    - [x] Wait for [CI](https://github.com/scala/scala3/actions/runs/12244900634) to publish artifacts
    - [x] Audit and release artifacts on https://oss.sonatype.org/

- [ ] On `lts-3.3` branch:
  - [ ] In `project/Build.scala`: Set `referenceVersion` to `3.3.5-RC1`
  - [ ] Check and update `project/MiMaFilters.scala`

- [x] Wait for releases/confirmation from tooling:
  - [x] Scala CLI - test
  - [x] Scala Native - publish compiler plugin
  - [x] Scastie - update available versions
  - [x] Scala DAP - [publish compiler plugin](https://github.com/scalacenter/scala-debug-adapter/actions/workflows/release-expression-compiler.yml)

- [x] Prepare draft of announcement blogpost for `3.3.5` on https://docs.scala-lang.org/
    
- [x] Announce the release
  - [x] Publish release on GitHub Releases (as pre-release)
  - [x] Create tracking thread on https://contributors.scala-lang.org
