### ISSUE TITLE
Scala 3.6.2 release procedure

### ISSUE THREAD

**Issue by WojciechMazur** [scala/scala3#22167]
- [x] Publish artifacts to Maven via CI
  - [x] Ensure scala-steward is [blocking automatic upgrades](https://github.com/scala-steward-org/scala-steward/blob/main/modules/core/src/main/resources/default.scala-steward.conf) for `3.6.2`
  - [x] On `release-3.6.2` branch:
    - [x] In `project/Build.scala`: Set `baseVersion = "3.6.2"`
    - [x] In `tasty/src/dotty/tools/tasty/TastyFormat.scala` ensure `ExperimentalVersion` is set to stable (0)
    - [x] Create changelog file in `changelogs/3.6.2.md`
    - [x] Tag the branch as `3.6.2`
    - [x] Wait for [CI](https://github.com/scala/scala3/actions/runs/12234321915) to publish artifacts 
    - [x] Audit and release artifacts on https://oss.sonatype.org/

- [x] Wait for releases/confirmation from tooling:
  - [x] Scala CLI - test
  - [x] Scala Native - publish compiler plugin
  - [ ] Scastie - update available versions
  - [x] Scala DAP - [publish compiler plugin](https://github.com/scalacenter/scala-debug-adapter/actions/workflows/release-expression-compiler.yml)

- [x] Prepare the documentation
  - [x] Generate stable documentation for `3.6.2` using scaladoc and upload to remote server to `3.6.2/` directory
  - [x] Add `3.6.2` to API docs `versions.json`
  - [x] Update symlink `3.x` to target `3.6.2/` directory

- [x] Announce the release
  - [x] Publish release on GitHub Releases (convert to public)
  - [x] Publish an announcement for `3.6.2` blogpost on https://scala-lang.org/blog/announcements/
  - [x] Update the tracking thread for `3.6.2` on https://contributors.scala-lang.org
  - [x] Update https://docs.scala-lang.org/:
    - [x] In `_config.yml` set `scala-3-version: 3.6.2`
    - [x] In `api/all.md` in `## Previous releases` section add entry for previous stable version 
    - [x] In `_overviews/jdk-compatibility/overview.md` - add entry for 3.6.2 if needed

- [x] Update the ecosystem
  - [x] Release `3.6.2` to SDKMAN
  - [x] Release `3.6.2` to Chocolatey
  - [x] Update the templates and examples projects:
    - [x] [scala3-mill-example-project](https://github.com/scala/scala3-mill-example-project)
    - [x] [scala3-cross.g8](https://github.com/scala/scala3-cross.g8)
    - [x] [scala3-staging.g8](https://github.com/scala/scala3-staging.g8)
    - [x] [scala3-tasty-inspector.g8](https://github.com/scala/scala3-tasty-inspector.g8)
    - [x] [scala3.g8](https://github.com/scala/scala3.g8)
  - [x] Update [Scala Steward config](https://github.com/scala-steward-org/scala-steward/blob/main/modules/core/src/main/resources/default.scala-steward.conf) https://github.com/scala-steward-org/scala-steward/:
    - [x] Unlock automatic upgrades for `3.6.2` - https://github.com/scala-steward-org/scala-steward/pull/3496
    - [x] Block automaitc upgrades for next planned version
  - [x] Update [Bazel Scala rules](https://github.com/bazelbuild/rules_scala) repositories config to use `3.6.2` - https://github.com/bazelbuild/rules_scala/pull/1672

**Comment by WojciechMazur** [comment]
> Will this update the Scala version list in IDEA?

Changes to InteliJ Scala plugin are not part of release procedure. In the future we might consider creating semi-automated PR as part of`update the ecosystem` step if the change would be trivial enough, altough currently I don't know what steps would be required on the InteliJ side
