### ISSUE TITLE
Scala 3.6.3-RC2 release procedure 

### ISSUE THREAD

**Issue by WojciechMazur** [scala/scala3#22280]
- [x] Publish artifacts to Maven via CI
  - [x] Ensure scala-steward is [blocking automatic upgrades](https://github.com/scala-steward-org/scala-steward/blob/main/modules/core/src/main/resources/default.scala-steward.conf) for `3.6.3`
  - [x] On `release-3.6.3` branch:
    - [x] In `project/Build.scala`: Set `baseVersion = "3.6.3-RC2"` and ensure `referenceVersion` is set to stable version
    - [x] In `tasty/src/dotty/tools/tasty/TastyFormat.scala` ensure `MinorVersion` is set to 6
    - [x] In `tasty/src/dotty/tools/tasty/TastyFormat.scala` ensure `ExperimentalVersion` is set to stable (0)
    - [x] Create changelog file in `changelogs/3.6.3-RC2.md`
    - [x] Tag the branch as `3.6.3-RC2`
    - [x] Wait for [CI to publish artifacts](https://github.com/scala/scala3/actions/runs/12549555460)
    - [x] Audit and release artifacts on https://oss.sonatype.org/

- [x] On `main` branch:
  - [x] In `project/Build.scala`: Set `referenceVersion` to `3.6.3-RC2`
  - [x] Check and update `project/MiMaFilters.scala`

- [ ] Wait for releases/confirmation from tooling:
  - [x] Scala CLI - test
  - [x] Scala Native - publish compiler plugin
  - [ ] Scastie - update available versions
  - [x] Scala DAP - [publish compiler plugin](https://github.com/scalacenter/scala-debug-adapter/actions/workflows/release-expression-compiler.yml)
  - [ ] Scalameta Parser - test

- [x] Announce the release
  - [x] Publish release on GitHub Releases (as pre-release)
  - [x] Update tracking thread on https://contributors.scala-lang.org
